using System.Collections.Generic;

namespace Dpr.AutomationFramework.Dpr.AutomationFramework.Intermediary.MortgageProductsTypes
{
    public class ResidentialList
    {
        public List<string> residentialProducts = new List<string>()
        {
            "Home Mover 75% Purchase Full Status Residential 2 Year Discounted Rate 1.50%",
            "Home Mover 95% Purchase Full Status Residential 2 Year Tracker Rate 1.55%",
            "First Time Buyer Help To Buy 80% Purchase Full Status Residential 2 Year Fixed Rate 1.60%",
            "First Time Buyer RTB 75% Purchase Full Status Residential 2 Year Fixed Rate 1.60%",
            "Home Mover 75% Purchase Full Status Residential 2 Year Fixed Rate 1.60% (Cashback £350)",
            "First Time Buyer RTB 75% Purchase Full Status Residential 2 Year Fixed Rate 1.80%",
            "First Time Buyer 80% Purchase Full Status Residential 2 Year Fixed Rate 1.80% (Free Legal)",
            "First Time Buyer Help To Buy 80% Purchase Full Status Residential 2 Year Fixed Rate 1.80% (Free Valuation)",
            "First Time Buyer 90% Purchase Full Status Residential 2 Year Fixed Rate 2.00% (Free Legal)",
            "First Time Buyer Shared Equity 90% Purchase Full Status Residential 2 Year Fixed Rate 2.25%",
            "First Time Buyer Shared Ownership 90% Purchase Full Status Residential 2 Year Fixed Rate 2.25%",
            "Home Mover 95% Purchase Full Status Residential 2 Year Fixed Rate 2.60% (Cashback £350)",
            "Home Buyer Shared Ownership 95% Purchase Full Status Residential 2 Year Fixed Rate 3.49%",
            "Home Buyer Shared Ownership 95% Shared Ownership Purchase Full Status Residential 2 Year Fixed Rate 3.49%",
            "Home Buyer Shared Equity 95% Purchase Full Status Residential 2 Year Fixed Rate 3.50%",
            "Home Buyer Shared Ownership 95% Shared Ownership Purchase Full Status Residential 2 Year Fixed Rate 3.60% (Cashback £200)",
            "Home Buyer Shared Equity 95% Purchase Full Status Residential 2 Year Fixed Rate 3.60%",
            "Home Buyer Shared Ownership 95% Purchase Full Status Residential 2 Year Fixed Rate 3.60% (Cashback £200)",
            "Home Mover 95% Purchase Full Status Residential 2 Year Discounted Rate 1.90%",
            "First Time Buyer Shared Ownership 90% Shared Ownership Purchase Full Status Residential 2 Year",
            "First Time Buyer Shared Ownership 90% Purchase Full Status Residential 2 Year Discounted Rate 2.00%",
            "First Time Buyer Shared Equity 90% Purchase Full Status Residential 2 Year Discounted Rate 2.00%",
            "First Time Buyer 90% Purchase Full Status Residential 5 Year Fixed Rate 2.50% (Free Legal)",
            "Home Mover 95% Purchase Full Status Residential 5 Year Fixed Rate 3.60% (Cashback £200)",
            "Home Buyer Shared Ownership 95% Shared Ownership Purchase Full Status Residential 5 Year Fixed Rate 4.10%",
            "Home Buyer Shared Ownership 95% Purchase Full Status Residential 5 Year Fixed Rate 4.10%",
            "Home Mover 95% Purchase Full Status Residential 5 Year Discounted Rate 2.20%",
            "Home Buyer Family Assist 95% Purchase Full Status Residential 5 Year Discounted Rate 2.40% (Free Legal)",
            "First Time Buyer Family Assist 90% Purchase Full Status Residential 5 Year Discounted Rate 2.75%",
            "First Time Buyer Family Assist 90% Purchase Full Status Residential 5 Year Fixed Rate 3.00%",
            "Home Mover 95% Purchase Full Status Residential Lifetime Tracker 2.25%",
            "Home Mover No Fees 75% Purchase Full Status Residential Standard Variable Rate 4.00%",
            "Home Mover No Fees 70% Purchase Full Status Residential Standard Variable Rate 4.00%",
            "Home Mover No Fees 90% Purchase Full Status Residential Standard Variable Rate 4.00%",
            "Home Mover No Fees 85% Purchase Full Status Residential Standard Variable Rate 4.00%",
            "Home Mover No Fees 80% Purchase Full Status Residential Standard Variable Rate 4.00%",
            "Home Mover No Fees 95% Purchase Full Status Residential Standard Variable Rate 4.00%",
            "Home Mover 95% Purchase Full Status Residential 2 Year Capped Rate 4.00%",
            "Home Mover No Fees 65% Purchase Full Status Residential Standard Variable Rate 4.00%",
            "Home Mover No Fees 60% Purchase Full Status Residential Standard Variable Rate 4.00%",
            "Home Mover 95% Purchase Full Status Residential 2 Year Discounted Rate 1.90%",
            "First Time Buyer Shared Ownership 90% Shared Ownership Purchase Full Status Residential 2 Year",
            "First Time Buyer Shared Ownership 90% Purchase Full Status Residential 2 Year Discounted Rate 2.00%",
            "First Time Buyer Shared Equity 90% Purchase Full Status Residential 2 Year Discounted Rate 2.00%",
            "First Time Buyer 90% Purchase Full Status Residential 5 Year Fixed Rate 2.50% (Free Legal)",
            "Home Mover 95% Purchase Full Status Residential 5 Year Fixed Rate 3.60% (Cashback £200)",
            "Home Buyer Shared Ownership 95% Shared Ownership Purchase Full Status Residential 5 Year Fixed Rate 4.10%",
            "Home Buyer Shared Ownership 95% Purchase Full Status Residential 5 Year Fixed Rate 4.10%",
            "Home Mover 95% Purchase Full Status Residential 5 Year Discounted Rate 2.20%",
            "Home Buyer Family Assist 95% Purchase Full Status Residential 5 Year Discounted Rate 2.40% (Free Legal)",
            "First Time Buyer Family Assist 90% Purchase Full Status Residential 5 Year Discounted Rate 2.75%",
            "First Time Buyer Family Assist 90% Purchase Full Status Residential 5 Year Fixed Rate 3.00%",
            "Home Mover 95% Purchase Full Status Residential Lifetime Tracker 2.25%",
            "Home Mover No Fees 75% Purchase Full Status Residential Standard Variable Rate 4.00%",
            "Home Mover No Fees 70% Purchase Full Status Residential Standard Variable Rate 4.00%",
            "Home Mover No Fees 90% Purchase Full Status Residential Standard Variable Rate 4.00%",
            "Home Mover No Fees 85% Purchase Full Status Residential Standard Variable Rate 4.00%",
            "Home Mover No Fees 80% Purchase Full Status Residential Standard Variable Rate 4.00%",
            "Home Mover No Fees 95% Purchase Full Status Residential Standard Variable Rate 4.00%",
            "Home Mover 95% Purchase Full Status Residential 2 Year Capped Rate 4.00%",
            "Home Mover No Fees 65% Purchase Full Status Residential Standard Variable Rate 4.00%",
            "Home Mover No Fees 60% Purchase Full Status Residential Standard Variable Rate 4.00%"
        };
    }
}
